apiVersion: v1
kind: Service
metadata:
  name: pipeline-api
  labels:
    app.kubernetes.io/name: pipeline-api
    app.kubernetes.io/component: pipeline
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pipeline-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
