apiVersion: v1
kind: Service
metadata:
  name: annotation-web
  labels:
    app.kubernetes.io/name: annotation-web
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: annotation-web
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
